// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApgvmEmkqKBtgM6ohIBlnjnvq4z2iNvWo',
    appId: '1:700894874458:web:5d851c46044e2e4bd14163',
    messagingSenderId: '700894874458',
    projectId: 'bhs-app-9fe52',
    authDomain: 'bhs-app-9fe52.firebaseapp.com',
    storageBucket: 'bhs-app-9fe52.appspot.com',
    measurementId: 'G-VLP37GRM1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3PX9NAtr9-l1BfSFOq3ydKDpyWRHveAQ',
    appId: '1:700894874458:android:b05f1675abe0eb85d14163',
    messagingSenderId: '700894874458',
    projectId: 'bhs-app-9fe52',
    storageBucket: 'bhs-app-9fe52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaFp_ECQ_tmdso_l9YbzAHoEUoYAmOG9s',
    appId: '1:700894874458:ios:437b5265b7decd93d14163',
    messagingSenderId: '700894874458',
    projectId: 'bhs-app-9fe52',
    storageBucket: 'bhs-app-9fe52.appspot.com',
    iosClientId: '700894874458-p1pc3qejsqkhtj385s11roked14dr5to.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaFp_ECQ_tmdso_l9YbzAHoEUoYAmOG9s',
    appId: '1:700894874458:ios:437b5265b7decd93d14163',
    messagingSenderId: '700894874458',
    projectId: 'bhs-app-9fe52',
    storageBucket: 'bhs-app-9fe52.appspot.com',
    iosClientId: '700894874458-p1pc3qejsqkhtj385s11roked14dr5to.apps.googleusercontent.com',
    iosBundleId: 'com.example.bhsApp',
  );
}
